package com.github.pixeldungeon;
import com.github.pixeldungeon.command.DungeonCommand; import com.github.pixeldungeon.manager.*; import org.bukkit.*; import org.bukkit.command.PluginCommand; import org.bukkit.plugin.java.JavaPlugin;
public class PixelDungeonPlugin extends JavaPlugin{
  private com.github.pixeldungeon.manager.PixelmonRuntimeBridge pixelmonBridge;
  private static PixelDungeonPlugin instance; public static PixelDungeonPlugin get(){return instance;}
  private DungeonManager dungeonManager; private PartyManager partyManager; private SelectionManager selectionManager; private GUIManager guiManager; private InstanceManager instanceManager; private RewardManager rewardManager; private RewardGUIManager rewardGUIManager; private LocaleManager localeManager; private NamespacedKey ticketKey; private RankingManager rankingManager; private HologramManager hologramManager; private WebhookManager webhookManager;
  public void onEnable(){ instance=this; saveDefaultConfig(); ticketKey=new NamespacedKey(this,"party_ticket"); selectionManager=new SelectionManager(); dungeonManager=new DungeonManager(this); partyManager=new PartyManager(); guiManager=new GUIManager(this); rewardManager=new RewardManager(this); instanceManager=new InstanceManager(this); rewardGUIManager=new RewardGUIManager(this); localeManager=new LocaleManager(this); rankingManager=new RankingManager(this); hologramManager=new HologramManager(this);
    webhookManager=new WebhookManager(this);
    Bukkit.getPluginManager().registerEvents(selectionManager,this); Bukkit.getPluginManager().registerEvents(guiManager,this); Bukkit.getPluginManager().registerEvents(instanceManager,this); Bukkit.getPluginManager().registerEvents(new PartyTicketListener(),this); Bukkit.getPluginManager().registerEvents(rewardGUIManager,this);
    PluginCommand root=getCommand("dungeon"); if(root!=null){ DungeonCommand ex=new DungeonCommand(this); root.setExecutor(ex); root.setTabCompleter(ex); } try{ pixelmonBridge=new com.github.pixeldungeon.manager.PixelmonRuntimeBridge(this); pixelmonBridge.tryInstall(); }catch(Throwable ignored){}
    getLogger().info("PixelDungeon enabled."); }
  public void onDisable(){ if(instanceManager!=null) instanceManager.shutdownAll(); getLogger().info("PixelDungeon disabled."); }
  public DungeonManager dungeonManager(){return dungeonManager;} public PartyManager partyManager(){return partyManager;} public SelectionManager selectionManager(){return selectionManager;} public GUIManager guiManager(){return guiManager;} public InstanceManager instanceManager(){return instanceManager;} public RewardManager rewardManager(){return rewardManager;} public RewardGUIManager rewardGUI(){return rewardGUIManager;} public LocaleManager localeManager(){return localeManager;} public NamespacedKey ticketKey(){return ticketKey;} public RankingManager rankingManager(){return rankingManager;} public HologramManager hologramManager(){return hologramManager;}
  public WebhookManager webhook(){ return webhookManager; }
}