# UserShop config
defaults:
  initial-slots: 9
  max-expansions: 5   # 0~5 (총 6단계) → 최대 54칸
  currency-name: "코인"

opener-item:
  name: "&a유저상점 오픈"
  lore:
    - "&7이 아이템을 들고 우클릭하면"
    - "&7유저상점이 열립니다."

tickets:
  register:
    name: "&b등록권"
    lore:
      - "&7유저상점에 물품 등록 가능"
  expand:
    name: "&e확장권"
    lore:
      - "&7유저상점 슬롯 +9"

gui:
  rows: 6 # 54칸
  controls:
    prev-slot: 45
    search-slot: 49
    next-slot: 53
  items:
    filler: BLACK_STAINED_GLASS_PANE
    prev: ARROW
    next: ARROW
    search: COMPASS
  titles:
    main: "&a유저상점 &7- 상점 목록 {page}"
    shop: "&b{owner}&7 님 상점 &7- 페이지 {page}"
    search: "&d검색 결과 &7- '{query}' &7페이지 {page}"
  lore:
    head:
      - "&7등록 상품: &f{count}개"
      - "&7최저가: &e{minPrice} {currency}"
      - "&8클릭: 상점 열기"
    item:
      - "&7판매자: &f{seller}"
      - "&7가격: &e{price} {currency} &7(1개당)"
      - "&7재고: &f{amount}개"
      - "&8좌클릭: 1개 구매"
      - "&8쉬프트-좌클릭: 64개 구매"
    item-korean:
      - "&7한글명: &f{kor}"

economy:
  enabled: true

search:
  aliases:
    PIXELMON_RARE_CANDY:
      ko: "이상한사탕"
      aliases: ["rare candy", "rare_candy", "레어캔디", "이사탕", "PIXLMON_RARE_CANDY"]
  korean-materials:
    DIAMOND: "다이아몬드"
    DIAMOND_SWORD: "다이아몬드 검"
    IRON_INGOT: "철 주괴"
    GOLD_INGOT: "금 주괴"
    EMERALD: "에메랄드"
    NETHER_STAR: "네더의 별"
    GOLDEN_APPLE: "황금 사과"
    ENCHANTED_GOLDEN_APPLE: "마법부여된 황금 사과"
    ROTTEN_FLESH: "썩은 살점"
    COBBLESTONE: "조약돌"
    OAK_LOG: "참나무 원목"
    OAK_PLANKS: "참나무 판자"
    STONE: "돌"
    DIAMOND_ORE: "다이아몬드 광석"
    IRON_ORE: "철 광석"
    GOLD_ORE: "금 광석"
    COAL: "석탄"
    COAL_ORE: "석탄 광석"
    LAPIS_LAZULI: "청금석"
    LAPIS_ORE: "청금석 광석"
    REDSTONE: "레드스톤 가루"
    REDSTONE_ORE: "레드스톤 광석"
    QUARTZ: "네더 석영"
    NETHER_QUARTZ_ORE: "네더 석영 광석"
