name: UserShop
main: com.minkang.ultimate.usershop.Main
version: 1.2.9
api-version: 1.16
author: minkang
softdepend: [Vault]
commands:
  "유저상점":
    description: 유저 상점/경매장
    usage: /유저상점
permissions:
  usershop.admin:
    description: 유저상점 관리자
    default: op
