name: UserShop
main: com.minkang.ultimate.usershop.Main
version: 1.0.0
api-version: 1.16
depend: [ProtocolLib]
softdepend: [Vault]
commands:
  유저상점:
    aliases: [usershop, shop]
    description: Open the user shop GUI
    permission: usershop.use
permissions:
  usershop.use:
    default: true
