name: PixelDungeon
main: com.github.pixeldungeon.PixelDungeonPlugin
version: 0.4.32
api-version: 1.16
author: PD-Team
softdepend: [Vault, WorldGuard]
commands:
  dungeon:
    aliases: [던전, d, dd]
permissions:
  pixeldungeon.user: {default: true}
  pixeldungeon.admin: {default: op}
