name: NBTGuard
main: com.minkang.nbtguard.NBTGuardPlugin
version: 1.0.0
api-version: 1.16
depend: [ProtocolLib]
commands:
  nbtguard:
    description: NBTGuard commands
    usage: /nbtguard
    permission: nbtguard.admin
permissions:
  nbtguard.admin:
    default: op
